### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by Tempest501** [fabiofenoglio/lelo-f1-hub#1]
I think it would be great if you can find a way to be able to use different patterns or create your own.

I think it would be really cool if we could sync the F1s up to some of the content that's available for things like the fleshlight launch etc.

You are a legend for looking into this!

**Comment by fabiofenoglio** [comment]
Hello @Tempest501 
thank you very much for your suggestions. 
I am working right now on a pattern editor; I will keep you updated.

Have a nice day

**Comment by fabiofenoglio** [comment]
Hi @Tempest501 , I extracted two features task from this issue.

I'm marking this as feature request and closing now, you can follow progress on this:

- https://github.com/fabiofenoglio/lelo-f1-hub/issues/4
- https://github.com/fabiofenoglio/lelo-f1-hub/issues/5

Thank you for your suggestion!

**Comment by Tempest501** [comment]
Your welcome , I should get some alone time later in the week so I will do some more testing.
________________________________

**Comment by fabiofenoglio** [comment]
Hi @Tempest501
The pattern management feature is ready to be tested. You can head to https://lelo-hub.fabiofenoglio.it/ in order to try it!
