### ISSUE TITLE
Feature request: Add up/down vote to shared sequences or star rating

### ISSUE THREAD

**Issue by silentinsight** [fabiofenoglio/lelo-f1-hub#10]
Create a voting system to provide feedback on shared custom sequences
consider star rating or up/down voting

**Comment by fabiofenoglio** [comment]
Excellent idea, I will insert this feature in the current sprint.
Thank you for your suggestion!

**Comment by fabiofenoglio** [comment]
Hi @silentinsight , rating for routines is now available!
You can head to https://lelo-hub.fabiofenoglio.it/sequence and start rating now ;)
