### ISSUE TITLE
Feature Request: Add written reviews to shared sequences

### ISSUE THREAD

**Issue by silentinsight** [fabiofenoglio/lelo-f1-hub#11]
Add the ability to leave reviews on shared sequences to provide feedback or review

**Comment by fabiofenoglio** [comment]
Nice idea. I will work on this after your star/upvote suggestion.
Thank you!

**Comment by jase1977** [comment]
My F1s won’t connect to the hub, I’ve tried turning it off and pressing the button after a refresh but no joy. What else can I try?

**Comment by fabiofenoglio** [comment]
Hi @jase1977 , please open an issue detailing your problem so we can move the discussion about it in a location ad-hoc
