### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by ZkilfinG** [fabiofenoglio/lelo-f1-hub#16]
This project looks like exactly what I was expecting F1s to have out of the box, excellent work! However, I'm not able to connect my device. I've tried restarting it in various ways and both from Chrome on my desktop PC (with bluetooth) and from iphone. On phone I don't get any device list like I do on desktop, but device list on desktop is always empty. I do have issues sometimes connecting device to the official app as well, but it usually works after restarting app+device. I also tried to see if I could see the F1s from phone or desktop normal bluetooth browse feature, but it doesn't show up, but maybe that's normal?

Any other suggestions I could try?

**Comment by fabiofenoglio** [comment]
Hello @ZkilfinG, thank you for your interest!
Are you able to connect to other bluetooth devices on your PC ?
Using the normal bluetooth browse feature I can see the F1s among the other devices, if you can't there is a good chance there could be a problem on your particular device.

**Comment by ZkilfinG** [comment]
Yes, tried now to connect my iphone and PC which worked. Iphone didn't show up in list on PC thou until I clicked the PC from the phone, and it seems there might be an issue on my desktop PC to discover devices. My laptop doesn't have that issue thou so tried it from there and there I can find and connect to F1s from Windows settings, but not through Chrome, but neither does Chrome discover any other BT devices even thou I can see them in the Windows settings, even when running some sample Chrome apps I found. Maybe those devices aren't compatible with Chrome BT API thou.

Lots of variables here, but in the end it does seem like both my desktop PC has issues with discovery in general AND my F1s isn't discoverable through Chrome API OR there is some compatibility issue in your implementation. I did drop a question to LELO support as well with a link to this issue so maybe we'll here something from them.

**Comment by fabiofenoglio** [comment]
Hello @ZkilfinG , any update on the issue?

**Comment by ZkilfinG** [comment]
Response from LELO was really lackluster sadly. The only decent info I got from them was that BT on desktop computers supposedly often have compability issues. I've pretty much given up and don't use my F1s anymore. Feel free to close this issue.

**Comment by jduba001** [comment]
I have the same issue, in reverse. I can connect to the Basic Controller from my MacBook Pro laptop, using Chrome or Safari, but I can't connect my iPhone 8 or iPhone 12 Pro to the Basic Controller with either browser, even though I can connect both phones to the LELO app. Anyone with similar problems or solutions?

**Comment by fabiofenoglio** [comment]
@jduba001 might be some iPhone security policy? I don't know because I never had one, so if anyone else had experience with iPhones please let us know.
