### ISSUE TITLE
Support for F1S V2?

### ISSUE THREAD

**Issue by slycooper724** [fabiofenoglio/lelo-f1-hub#18]
Is there support for the new F1S V2, and if not how long do you think it will take to implement the new release given our current infrastructure and code that's running?

**Comment by fabiofenoglio** [comment]
Hello @slycooper724 , if the Bluetooth interface for the F1S V2 is compatible with the one of the previous model, it should work out of the box. 
The current HUB should already be able to connect to the new device.
In case of relevant hardware or software differences minimal adjustments would be needed but I'm not able to give you a detailed estimate without the specifications (I see no updates yet on LELO's GitHub page).

If you own F1S V2 device and have problems using it with the Hub, please feel free to open an issue to ask for help.

**Comment by slycooper724** [comment]
I was just curious as I saw they released a new version of the F1s, I'll let you know when I look into it if they are in fact compatible or not.
