### ISSUE TITLE
Remote Access

### ISSUE THREAD

**Issue by slycooper724** [fabiofenoglio/lelo-f1-hub#2]
I think there should be a way for someone to remotely control the F1s from the hub. Now that you implemented an account based system, starting a shared session could be easier and not have to expose your IP. This isn't a concern for me, but I see how it could be for other users, so I thought I might put it out there as good for thought. @fabiofenoglio Amazing production time as well, how long did it take you to develop the hub?
Thanks!
Sly

**Comment by fabiofenoglio** [comment]
Hi @slycooper724 
I will work on a shared remote control. Thank you for your suggestion!

Thank you, the application was actually generated pretty quickly thanks to https://www.jhipster.tech/, most of the time I spent was on customization and preparation before publishing.

**Comment by fabiofenoglio** [comment]
Hi @slycooper724 , I extracted two features task from this issue.

I'm marking this as feature request and closing now, you can follow progress on this:

- https://github.com/fabiofenoglio/lelo-f1-hub/issues/7

Thank you for your suggestion!
