### ISSUE TITLE
F1S V2 support

### ISSUE THREAD

**Issue by fabiofenoglio** [fabiofenoglio/lelo-f1-hub#20]
The newer version of the device (F1S V2, the blue one) is currently not supported as BLE specifications have not yet been published.

Please follow this thread to be kept up to date on F1S V2 support.

Please comment here if you have any questions regarding this topic.

**Comment by yomli** [comment]
The F1sV2 BLE specs seems [to be here](https://github.com/LELO-Devs/F1S-SDK/blob/master/F1S-V2-SPEC.md) (updated 4 days ago).

**Comment by fabiofenoglio** [comment]
@yomli thank you very much for the pointer, I'll start implementing propert F1sV2 support once back from the holidays

**Comment by fabiofenoglio** [comment]
Started working on F1sV2 support today

**Comment by yomli** [comment]
Thanks a lot. I'll try to find the time to beta test that.

**Comment by JoostvL** [comment]
I could beta test it as well, just let me know when and where.

Kudos for this project btw.

**Comment by adamsummers1** [comment]
likewise - interested to help/test
________________________________

**Comment by fabiofenoglio** [comment]
Thank you everyone.
I started working on the standalone web sdk project (since lelo-hub is based on that):
https://github.com/fabiofenoglio/lelo-f1-web-sdk
I'll post updates as soon as I'll figure out how to complete the connection to the device succesfully.

The latest version is testable here: https://fabiofenoglio.github.io/lelo-f1-web-sdk/example.html
but it's currently having troubles writing to the security registry and reading the battery level

**Comment by JoostvL** [comment]
Using https://fabiofenoglio.github.io/lelo-f1-web-sdk/example.html my Desktop cannot find the device at all, my android phone does find it, is able to read the battery level but disconnect right after:
![F1](https://user-images.githubusercontent.com/23191666/133667369-c390e669-b676-4794-8cb5-fd26b4c932af.jpg)

Let me know if you need any extra information.

**Comment by paulioliolio** [comment]
Exactly the same behaviour as Joost is experiencing. 
![Screenshot_20211020-173921_Chrome](https://user-images.githubusercontent.com/6709056/138135905-add96ebf-5c7c-475c-8093-d8941fcf2be6.jpg)
 The error is truncated, cannot find a way to get the full message! But more here: `disconnecting` after error: NetworkError: Failed to execute 'readValue' on ' ``
 
It goes on to say can't perform GATT operations or something to that effect.

Hope this helps!

**Comment by Plutoonas** [comment]
hi how are you doing with v2 support?  maybe there is any news?

**Comment by Plutoonas** [comment]
hi how are you doing with v2 support?  maybe there is any news? =)

**Comment by F1masturber** [comment]
Hi, Im not a programator but my F1s V2 device is turning of after pressing central button to authorize. If will authorization making by + or - button maybe will by everityng working properly.

**Comment by fabiofenoglio** [comment]
hello everyone,
support for V2 is progressing slower than expected due to personal issues... but it's progressing.

I'll be sure to keep you up to date with news

**Comment by ZZR1200** [comment]
Been a while since a V2 update. Any new estimate on a timeline. Love the V1 version of this tool and looking forward to the V2!

**Comment by WSecret** [comment]
Any updates on V2 support? Let me know if there’s anything I can help with

**Comment by ahezard** [comment]
I was able to found a very simple solution to make the SDK web client works with the F1SV2. The code for the F1Sv2 connection, was correct, the issue was the debugging code displaying the value of the password that was interfering with the connection code. I submitted a pull request.

**Comment by fabiofenoglio** [comment]
closing this issue as the project is shutting down. 

See [website](https://lelo-hub.fabiofenoglio.it) for full announcement
