### ISSUE TITLE
User Agent Detection

### ISSUE THREAD

**Issue by slycooper724** [fabiofenoglio/lelo-f1-hub#3]
If the hub detected the user agent of my browser to direct me to the best fitting version of the controller(mobile vs. desktop), that would be amazing.
Best Regards,
Sly

**Comment by fabiofenoglio** [comment]
Hi, the latest version is actually built on a responsive template and should behave differently on mobile vs desktop. Please let me know if that does not work for you

**Comment by slycooper724** [comment]
Oh, That is great! I should have guessed after looking at it on both platforms.

**Comment by fabiofenoglio** [comment]
Hi @slycooper724 , I extracted a single feature task from this issue.

I'm marking this as feature request and closing now, you can follow progress on this:
https://github.com/fabiofenoglio/lelo-f1-hub/issues/6

Thank you for your suggestion!

**Comment by fabiofenoglio** [comment]
Hi @slycooper724,
just wanted to let you know that the new pattern management feature is ready to be tested.
You can head to https://lelo-hub.fabiofenoglio.it/ in order to try it!
